name: Swift

on: [push]

jobs:
  test:
    name: test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1

    - uses: ./.github/actions/testing-action
